# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-22 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20160822_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.FileField(upload_to='portfolio/static/media/2016_08_22'),
        ),
    ]
