# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-22 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20160822_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='portfolio/static/portfolio/media/'),
        ),
    ]
