# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-02 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_post_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
    ]
