# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160513_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=100, populate_from='headline'),
        ),
    ]
