# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160523_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='preview',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
